<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ac642bd4-760e-404b-86ce-fe55af25364d</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="8.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Leaxilearn.LibreTranslate\Leaxilearn.LibreTranslate.csproj" />
    <ProjectReference Include="..\Lexilearn.Application\Lexilearn.Application.csproj" />
    <ProjectReference Include="..\Lexilearn.Identity\Lexilearn.Identity.csproj" />
    <ProjectReference Include="..\Lexilearn.MySql\Lexilearn.MySql.csproj" />
    <ProjectReference Include="..\Lexilearn.Shared\Lexilearn.Shared.csproj" />
  </ItemGroup>

</Project>
